[project]
name = "ray_tracer"
version = "0.0.1"
authors = ["M. Rozycki <mar.rozycki@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.3", features = ["yaml"] }
rand = "0.7.3"
itertools = "0.9.0"
nalgebra = "0.23.1"
png = "0.16.7"
rayon = "1.5.0"
